### PR TITLE
fix "multiple same users"

### LINKED ISSUE #11: Prevent adding user to users if it has already logged in
Is this a good idea? Want to know what you think about it.
multiple_mes

### PR DESCRIPTION
**Pull request by JasonJunJun**
fix #11

### CODE REVIEW

File: reducers/sessionReducer.js [hunk 1]
```diff
@@ -31,6 +37,9 @@ export default (state, action) => {
       return state;
     case UPDATE_CURRENT_USER:
       return Object.assign({}, state, { user: action.user });
+    case USER_ALREADY_LOGGED_IN:
+      // todo: hide everything, display message
```
Comment (JasonJunJun) [inline reducers/sessionReducer.js]: Something like the below image, but I don't know much about UI stuff.

image

File: server/api.js [hunk 2]
```diff
@@ -151,23 +151,37 @@ const exportedApi = io => {
...
-          Date.now() - playingContext.startTimestamp
-        );
+
+      if (index !== -1) {
+        // user has already logged in
+        socket.emit('user has already logged in');
+      } else {
+        // user hasn't logged in
+        users.push({
+          // todo: modify structure, user attribute inside users?
```
Comment (JasonJunJun) [inline server/api.js]: `users` has an attribute `user`, it's a little confusing.

File: reducers/sessionReducer.js (hunk 1 above)
Comment (JMPerez) [reply reducers/sessionReducer.js]: IMHO a better solution would allow the user to control the player from another tab, but reuse the same refresh token. Even better, it should be possible to just remove duplicates from the list of users.

I can imagine some users will have many tabs on several windows/browsers. Also, it might be that the are logged in on another device. It might be more user friendly to let them use the site and handle the duplicates in the app, instead of moving the burden to the user.

Comment (JasonJunJun) [reply reducers/sessionReducer.js]: Yes, you're right. But maybe we should control some actions like "play track". Imagine that a user have multiple tabs, every tab will receive a "play track" message. But it will bring a lot of complexity in order to control this behavior. What do you think? Is multiple "play track" messages acceptable?

Comment (JMPerez) [reply reducers/sessionReducer.js]: I see your point. There would be multiple tabs sending play commands, which might not get them exactly at the same time. The backend could be smart enough to only send it to one of the users from the duplicated set, though I don't know if this is overcomplicating things.

In general I prefer to put logic in the server rather than making the user think and find out what's going on.

What do you think?

Comment (JasonJunJun) [reply reducers/sessionReducer.js]: Yes, it's better to do these things in server side. So one solution is to retrofit `user`, it has a `sockets` attributes which contains an array of sockets associated with the user. When sending `play track` command, don't simply use `broadcast`, instead, iterate `users`, for each user, pick one of those sockets to send `play track` command.

Is this a good solution?

Comment (JMPerez) [reply reducers/sessionReducer.js]: Yes, that sounds great!

Comment (JasonJunJun) [reply reducers/sessionReducer.js]: solve this problem in a new commit. Hope that it's good to go. 😂

File: server/api.js (hunk 2 above)
Comment (JasonJunJun) [reply server/api.js]: change this in a new commit.

File: server/models/Bot.js [hunk 3]
```diff
@@ -29,7 +29,8 @@ class Bot {
     return {
       id: this.id,
       images: [{ url: this.image }],
-      type: 'robot'
+      type: 'robot',
+      socketIdArray: [] // todo: always empty, add this attribute in order to be compatible with other true users
```
Comment (JasonJunJun) [inline server/models/Bot.js]: If this is okay, feel free to delete `todo`.

File: server/api.js [hunk 4]
```diff
@@ -50,19 +50,26 @@ const botUser = new Bot({
...
 const queueManager = new QueueManager({
   onPlay: () => {
     const { track, user } = queueManager.getPlayingContext();
-    globalSocket && globalSocket.emit('play track', track, user);
-    globalSocket && globalSocket.broadcast.emit('play track', track, user);
+    // if one user logs in on multiple tabs, just send 'play track' message to one tab,
+    // but need to send 'update now playing' to other tabs
+    users.forEach(u => {
+      u.socketIdArray.forEach((socketId, index) => {
+        if (index === 0) {
```
Comment (JMPerez) [inline server/api.js]: The user playing the track doesn't necessarily need to be in the first position of the array, right?

Comment (JasonJunJun) [reply server/api.js]: I don't quite understand, what is the user playing the track? Does it mean the user who added the song?

The `socketIdArray` of the `user` is the user's all related sockets. I just need to pick one (it's easy to pick the first one) to send `play track` message, and send `update now playing` to other sockets. Am I wrong?

Comment (JasonJunJun) [reply server/api.js]: Any update, maybe you're busy.

Comment (JMPerez) [reply server/api.js]: My bad, sorry! I don't know why I thought that the index was the index for the user, but it's that index of the socket
